name: ðŸ Firmware builder

on:
  push:
    paths: 
      - '.github/workflows/firmware.yaml'
      - 'firmware/**'

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: docker.io/zmkfirmware/zmk-build-arm:3.5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clone ZMK
        run: | 
          git clone https://github.com/zmkfirmware/zmk.git firmware/ws-1/zmk
          cp -r firmware/ws-1/app firmware/ws-1/zmk

      - name: Add vendor prefix
        run: echo "etzee  etzee" >> firmware/ws-1/zmk/app/dts/bindings/vendor-prefixes.yaml

      - name: Initialize workspace (west init)
        working-directory: firmware/ws-1/zmk
        run: west init -l app

      - name: Update modules (west update)
        working-directory: firmware/ws-1/zmk
        run: west update

      - name: Export Zephyr CMake package (west zephyr-export)
        working-directory: firmware/ws-1/zmk
        run: west zephyr-export

      - name: Build firmware (west build)
        working-directory: firmware/ws-1/zmk/app
        run: |
          echo "::notice:: Building firmware for ${{ github.event_name }}."

          west build -b etzee_101 -- \
          -DEXTRA_CONF_FILE=boards/arm/etzee_101/left.conf \
          -DEXTRA_DTC_OVERLAY_FILE=boards/arm/etzee_101/left.overlay \
          -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware-output
          path: |
            firmware/ws-1/zmk/app/build/zephyr/*.uf2 \
            firmware/ws-1/zmk/app/build/compile_commands.json
